# Generated by Django 4.2 on 2024-03-17 10:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_Creating_company_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientCategory',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_client_category', to='company.company')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ledger',
            fields=[
                ('ledger_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('ledger_code', models.CharField(max_length=250)),
                ('ledger_name', models.CharField(max_length=250)),
                ('overdue_bills', models.IntegerField(blank=True, default=0, null=True)),
                ('pending_bills', models.IntegerField(blank=True, default=0, null=True)),
                ('cleared_bills', models.IntegerField(blank=True, default=0, null=True)),
                ('all_bills', models.IntegerField(blank=True, default=0, null=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('phone_number', models.CharField(blank=True, max_length=250, null=True)),
                ('pin_no', models.CharField(blank=True, max_length=250, null=True)),
                ('amt_overdue', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('email', models.CharField(blank=True, max_length=250, null=True)),
                ('status', models.CharField(choices=[('', 'Select Financial Statement'), ('Balance Sheet', 'Balance Sheet'), ('Income Statement', 'Income Statement')], default='', max_length=250)),
                ('contact_person', models.CharField(blank=True, max_length=250, null=True)),
                ('inv_address', models.CharField(blank=True, max_length=250, null=True)),
                ('ship_address', models.CharField(blank=True, max_length=250, null=True)),
                ('client_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_type_ledger', to='financial_accounts_chart_of_accounts.clientcategory')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_ledger', to='company.company')),
            ],
            options={
                'ordering': ['ledger_name'],
            },
        ),
    ]
