# Generated by Django 4.2 on 2024-03-18 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0001_Creating_Client_Category_and_Ledger_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='ledger',
            name='financial_statement',
            field=models.CharField(choices=[('', 'Select Financial Statement'), ('Balance Sheet', 'Balance Sheet'), ('Income Statement', 'Income Statement')], default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='ledger',
            name='status',
            field=models.CharField(choices=[('', 'Select Status'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=250),
        ),
    ]
