# Generated by Django 4.2 on 2024-03-20 04:42

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('financial_accounts_chart_of_accounts', '0003_Adding_ledger_type_to_ledgers_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ledger',
            options={'ordering': ['ledger_type', 'ledger_code']},
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('journal_no', models.CharField(max_length=250)),
                ('client', models.CharField(blank=True, max_length=250, null=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=250)),
                ('description', models.TextField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_journal', to='company.company')),
                ('journal_ledger', models.ManyToManyField(to='financial_accounts_chart_of_accounts.ledger')),
            ],
            options={
                'ordering': ['issue_date', 'journal_no'],
            },
        ),
    ]
