# Generated by Django 4.2 on 2024-03-21 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0005_Creating_journal_entry_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='journal_ledger',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='description',
            field=models.TextField(default='journal entry'),
            preserve_default=False,
        ),
    ]
