# Generated by Django 4.2 on 2024-03-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0006_Adding_description_field_to_journal_entry_table_and_removing_ledgers_from_journals_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='done_by',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='banking_date',
            field=models.DateField(default='2024-01-01'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journalentry',
            name='txn_type',
            field=models.CharField(choices=[('', 'Select Txn Type'), ('BAL', 'BAL'), ('JNL', 'JNL'), ('INV', 'INV'), ('RCPT', 'RCPT'), ('PMT', 'PMT')], default='JNL', max_length=250),
        ),
    ]
