# Generated by Django 4.2 on 2024-03-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0009_alter_journal_due_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='txn_type',
            field=models.CharField(choices=[('', 'Select Txn Type'), ('BAL', 'BAL'), ('JNL', 'JNL'), ('INV', 'INV'), ('RCPT', 'RCPT'), ('PMT', 'PMT')], default='JNL', max_length=250),
        ),
    ]
