# Generated by Django 4.2 on 2024-03-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0010_Adding_transaction_type_field_to_journals_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='journal_no',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
