# Generated by Django 4.2 on 2024-03-22 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0011_Making_journal_no_field_null_in_journals_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='journal',
            options={'ordering': ['-journal_no']},
        ),
    ]
