# Generated by Django 4.2 on 2024-03-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0012_Adding_ledger_id_to_patients_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='client_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
