# Generated by Django 4.2 on 2024-03-27 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0013_Adding_client_id_field_to_journals_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ledger',
            name='ledger_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
