# Generated by Django 4.2 on 2024-03-28 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0014_Making_ledger_code_field_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='payment_method',
            field=models.CharField(choices=[('', 'Select Payment Method'), ('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Bank Deposit', 'Bank Deposit'), ('Cheque', 'Cheque'), ('Cheque', 'Cheque'), ('RTGS', 'RTGS'), ('EFT', 'EFT')], default='', max_length=250),
        ),
    ]
