# Generated by Django 4.2 on 2024-03-28 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial_accounts_chart_of_accounts', '0015_Adding_payment_method_field_to_journals_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('', 'Select Payment Method'), ('Cash', 'Cash'), ('Mpesa', 'Mpesa'), ('Bank Deposit', 'Bank Deposit'), ('Cheque', 'Cheque'), ('Check-off', 'Check-off'), ('RTGS', 'RTGS'), ('EFT', 'EFT')], default='', max_length=250, null=True),
        ),
    ]
