# Generated by Django 4.2 on 2024-03-01 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='allowed_company',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='user_company', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default.png', upload_to='profile_pics'),
        ),
    ]
