# Generated by Django 4.2 on 2024-02-24 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0002_Removing_manager_table'),
        ('users', '0004_Adding_departments_field_to_users_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('start_date', models.DateField()),
                ('phone_number', models.CharField(max_length=250)),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Active', 'Active'), ('Inactive', 'Inactive')], default='', max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dep_manager', to='xtra.department')),
            ],
        ),
    ]
