# Generated by Django 4.2 on 2024-03-04 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('users', '0004_Adding_user_department_name_field_to_users_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='company',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='manager_company', to='company.company'),
            preserve_default=False,
        ),
    ]
