# Generated by Django 4.2 on 2024-03-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_Adding_company_field_to_department_manager_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='manager_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
