# Generated by Django 4.2 on 2024-02-24 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_Adding_manager_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manager',
            options={'ordering': ['-start_date']},
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='user_manager', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='manager',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
