# Generated by Django 4.2 on 2024-03-14 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('xtra', '0002_alter_department_code'),
        ('patients_registration', '0007_Adding_start_date_field_to_patients_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('room_code', models.CharField(max_length=100, unique=True)),
                ('room_name', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_room', to='xtra.department')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_room', to='patients_registration.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_room', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['room_name'],
            },
        ),
    ]
