# Generated by Django 4.2 on 2024-03-14 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('rooms', '0001_Creating_a_rooms_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='company',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='company_room', to='company.company'),
            preserve_default=False,
        ),
    ]
