# Generated by Django 4.2 on 2024-03-15 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_Creating_a_wards_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='staff',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
