# Generated by Django 4.2 on 2024-03-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_Changing_staff_field_from_fk_to_charfield_rooms_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='department_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
