# Generated by Django 4.2 on 2024-03-15 09:06

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0007_Adding_start_date_field_to_patients_table'),
        ('rooms', '0006_Adding_ward_code_to_wards_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('bed_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('bed_number', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('', 'Select Status'), ('Available', 'Available'), ('Occupied', 'Occupied'), ('Reserved', 'Reserved')], default='', max_length=250)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_bed', to='patients_registration.patient')),
                ('ward', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ward_beds', to='rooms.ward')),
            ],
        ),
    ]
