# Generated by Django 4.2 on 2024-03-17 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0009_Changing_default_for_bed_status_in_bed_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bed',
            options={'ordering': ['ward', 'bed_number']},
        ),
        migrations.AlterField(
            model_name='bed',
            name='bed_number',
            field=models.IntegerField(),
        ),
    ]
