# Generated by Django 4.2 on 2024-03-08 15:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients_registration', '0001_Creating_required_tables_for_handling_patients'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientBill',
            fields=[
                ('patient_bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_payable', models.DecimalField(decimal_places=2, max_digits=10)),
                ('health_insurance', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_health_insurance', to='patients_registration.healthinsurance')),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_bill_history', to='patients_registration.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='PatientBillPaymentHistory',
            fields=[
                ('patient_bill_payment_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('patient_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('insurance_paid', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('patient_bill', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_bills', to='billing_management.patientbill')),
            ],
        ),
    ]
