# Generated by Django 4.2 on 2024-03-20 05:00

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('financial_accounts_chart_of_accounts', '0004_Creating_journals_table'),
        ('billing_management', '0001_Creating_the_required_tables_for_patient_billing'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalFee',
            fields=[
                ('fees_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('fee_name', models.CharField(max_length=250)),
                ('default_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_medical_fees', to='company.company')),
                ('posting_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fees_posting_account', to='financial_accounts_chart_of_accounts.ledger')),
            ],
            options={
                'ordering': ['fee_name'],
            },
        ),
    ]
