# Generated by Django 4.2 on 2024-03-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing_management', '0002_Creating_Medical_Fees_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientbill',
            name='patient_history',
        ),
    ]
