# Generated by Django 4.2 on 2024-03-09 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0001_Creating_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='code',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
