# Generated by Django 4.2 on 2024-02-24 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0001_creating_departments_and_managers_tables'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
