# Generated by Django 4.2 on 2024-03-01 09:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=250)),
                ('town', models.CharField(max_length=250)),
                ('logo', models.ImageField(default='default_logo.png', upload_to='company_pics')),
                ('email', models.EmailField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('kra_pin', models.CharField(max_length=250)),
                ('registration_number', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
