# Generated by Django 4.2 on 2024-03-08 15:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctor_profile', '0003_Creating_doctor_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContactPerson',
            fields=[
                ('contact_person_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='HealthInsurance',
            fields=[
                ('health_insurance_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('company', models.CharField(max_length=250)),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=250)),
                ('last_name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('birth_date', models.DateField()),
                ('city', models.CharField(max_length=250)),
                ('address', models.CharField(max_length=250)),
                ('country', models.CharField(max_length=250)),
                ('emergency_contact_person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_contact_person', to='patients_registration.emergencycontactperson')),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('patient_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_history', to='doctor_profile.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='patients_registration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientFollowupHistory',
            fields=[
                ('patient_followup_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history', to='patients_registration.patienthistory')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosisHistory',
            fields=[
                ('patient_diagnosis_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_diagnosis_history', to='doctor_profile.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis_history', to='patients_registration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdmissionHistory',
            fields=[
                ('patient_admission_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ward_no', models.CharField(max_length=250)),
                ('bed_no', models.CharField(max_length=250)),
                ('patient_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission_history', to='patients_registration.patienthistory')),
            ],
        ),
    ]
