# Generated by Django 4.2 on 2024-03-09 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('patients_registration', '0001_Creating_required_tables_for_handling_patients'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontactperson',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='emmergency_contact_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='healthinsurance',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='health_insurance_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='patient_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientadmissionhistory',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientdiagnosishistory',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientfollowuphistory',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='patient_follow_up_hospital', to='company.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patienthistory',
            name='hospital',
            field=models.ForeignKey(default='9e14bcef-d3c1-400c-a8c0-66d7b25cc5ff', on_delete=django.db.models.deletion.CASCADE, related_name='patient_history_hospital', to='company.company'),
            preserve_default=False,
        ),
    ]
