# Generated by Django 4.2 on 2024-03-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0002_Adding_hospital_field_to_all_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='id_number',
            field=models.CharField(default='111111', max_length=250),
            preserve_default=False,
        ),
    ]
