# Generated by Django 4.2 on 2024-03-10 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0003_Adding_id_number_field_to_patient_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='emergency_contact_person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='patient_contact_person', to='patients_registration.emergencycontactperson'),
        ),
    ]
