# Generated by Django 4.2 on 2024-03-12 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0004_Allowing_patient_emergency_contact_field_be_blank_or_null'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencycontactperson',
            name='patient',
            field=models.CharField(default='Default Patient', max_length=250),
            preserve_default=False,
        ),
    ]
