# Generated by Django 4.2 on 2024-03-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('patients_registration', '0007_Adding_start_date_field_to_patients_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emergencycontactperson',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_hospital', to='company.company'),
        ),
    ]
