# Generated by Django 4.2 on 2024-03-20 08:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0010_Change_meta_options_on_patient_history_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_historical_data', to='patients_registration.patient'),
        ),
    ]
