# Generated by Django 4.2 on 2024-03-20 17:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0003_Creating_doctor_table'),
        ('patients_registration', '0012_Adding_staff_field_to_patient_history_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patienthistory',
            name='doctor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_history', to='doctor_profile.doctor'),
        ),
    ]
