# Generated by Django 4.2 on 2024-03-21 05:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0013_Altering_doctor_field_in_patient_history_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patienthistory',
            options={},
        ),
        migrations.RemoveField(
            model_name='patientadmissionhistory',
            name='patient_history',
        ),
        migrations.RemoveField(
            model_name='patientfollowuphistory',
            name='patient_history',
        ),
    ]
