# Generated by Django 4.2 on 2024-03-21 05:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('doctor_profile', '0003_Creating_doctor_table'),
        ('company', '0001_Creating_company_table'),
        ('patients_registration', '0015_Removing_patient_history_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('patient_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('date', models.DateField()),
                ('notes', models.TextField()),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_history_doctor', to='doctor_profile.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history_hospital', to='company.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_history_patient', to='patients_registration.patient')),
                ('staff', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_history_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'patient'],
            },
        ),
    ]
