# Generated by Django 4.2 on 2024-03-21 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0016_Recreating_patients_history_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patienthistory',
            name='doctor',
        ),
    ]
