# Generated by Django 4.2 on 2024-03-23 04:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0019_Adding_ledger_id_to_patients_table'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PatientFollowupHistory',
        ),
    ]
