# Generated by Django 4.2 on 2024-03-23 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0020_Removing_followup_history_table_to_fix_bug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientdiagnosishistory',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='patientdiagnosishistory',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='patientdiagnosishistory',
            name='patient',
        ),
        migrations.DeleteModel(
            name='PatientAdmissionHistory',
        ),
        migrations.DeleteModel(
            name='PatientDiagnosisHistory',
        ),
    ]
