# Generated by Django 4.2 on 2024-03-23 04:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0003_Creating_doctor_table'),
        ('company', '0001_Creating_company_table'),
        ('patients_registration', '0021_Removing_patient_admission_and_diagnosis_tables_to_fix_bug'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientFollowupHistory',
            fields=[
                ('patient_followup_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_follow_up_hospital', to='company.company')),
            ],
        ),
        migrations.CreateModel(
            name='PatientDiagnosisHistory',
            fields=[
                ('patient_diagnosis_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('date', models.DateField()),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='doctor_diagnosis_history', to='doctor_profile.doctor')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis_hospital', to='company.company')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_diagnosis_history', to='patients_registration.patient')),
            ],
        ),
        migrations.CreateModel(
            name='PatientAdmissionHistory',
            fields=[
                ('patient_admission_history_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('admission_date', models.DateField()),
                ('discharge_date', models.DateField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ward_no', models.CharField(max_length=250)),
                ('bed_no', models.CharField(max_length=250)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_admission_hospital', to='company.company')),
            ],
        ),
    ]
