# Generated by Django 4.2 on 2024-03-25 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients_registration', '0022_Recreating_followup_admission_and_diagnosis_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_code',
            field=models.CharField(max_length=250, unique=True),
        ),
    ]
