# Generated by Django 4.2 on 2024-03-12 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_Creating_appointments_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='doctor_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
