# Generated by Django 4.2 on 2024-03-21 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_Adding_time_field_to_appointments_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appointment',
            options={'ordering': ['-date']},
        ),
    ]
