# Generated by Django 4.2.4 on 2024-02-09 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('manager', models.CharField(max_length=250)),
                ('manager_start_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payroll_number', models.CharField(max_length=250)),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='doctor_profile.department')),
            ],
        ),
    ]
