# Generated by Django 4.2 on 2024-03-01 09:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('payroll_number', models.CharField(blank=True, max_length=250)),
                ('first_name', models.CharField(default='', max_length=250)),
                ('last_name', models.CharField(default='', max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('specialization', models.CharField(blank=True, max_length=250)),
                ('phone_number', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
    ]
