# Generated by Django 4.2 on 2024-02-13 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0001_creating_department_and_doctor_tables'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='doctor_profile.department'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='payroll_number',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialization',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
