# Generated by Django 4.2 on 2024-03-01 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_Creating_company_table'),
        ('xtra', '0001_Creating_department_table'),
        ('doctor_profile', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, default='bd30226f-c2ff-4059-bec1-27c5a53e00a6', on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='xtra.department'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='doctor',
            name='hospital',
            field=models.ForeignKey(default='5eec8557-9d5e-4af7-8d86-a61f90e84427', on_delete=django.db.models.deletion.CASCADE, related_name='doctor_hospital', to='company.company'),
            preserve_default=False,
        ),
    ]
