# Generated by Django 4.2 on 2024-02-14 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0003_adding_user_field_to_doctor_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='department',
        ),
    ]
