# Generated by Django 4.2 on 2024-02-15 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0005_adding_department_manager_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
    ]
