# Generated by Django 4.2 on 2024-02-16 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0007_creating_department_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['id']},
        ),
    ]
