# Generated by Django 4.2 on 2024-02-22 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor_profile', '0008_changed_ordering_for_departments_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='department',
        ),
        migrations.AlterModelOptions(
            name='doctor',
            options={'ordering': ['id']},
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Manager',
        ),
    ]
