# Generated by Django 4.2 on 2024-02-22 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('xtra', '0001_creating_departments_and_managers_tables'),
        ('doctor_profile', '0009_removing_departments_and_managers_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='department',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='xtra.department'),
            preserve_default=False,
        ),
    ]
